# Generated by Django 3.2.8 on 2021-10-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='manage_models.Categoria'),
        ),
    ]
