# Generated by Django 3.2.8 on 2021-10-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_models', '0002_alter_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='descripcion',
            new_name='nombre',
        ),
    ]
