# Generated by Django 3.2.8 on 2021-10-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_models', '0003_rename_descripcion_marca_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
