# Generated by Django 3.2.8 on 2021-10-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_models', '0006_auto_20211019_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortecaja',
            name='caja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_models.caja'),
        ),
    ]
