# Generated by Django 3.2.8 on 2021-10-21 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_models', '0008_alter_cortecaja_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortecaja',
            name='estado',
        ),
        migrations.AddField(
            model_name='caja',
            name='estado',
            field=models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], default=('C', 'Cerrada'), max_length=1),
        ),
        migrations.AlterField(
            model_name='cortecaja',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_models.caja'),
        ),
    ]
