# Generated by Django 3.2.8 on 2021-10-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_models', '0010_alter_caja_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='estado',
            field=models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], default=('C', 'Cerrada'), max_length=1),
        ),
    ]
