# Generated by Django 3.2.8 on 2021-10-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_models', '0012_alter_caja_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cortecaja',
            name='saldo_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
