# Generated by Django 3.2.8 on 2021-10-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_models', '0014_alter_cortecaja_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='manage_models.venta'),
        ),
    ]
